=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/game.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
  "title": "Cosmic Reach language (game.json)",
  "description": "FinalForEach's Cosmic Reach game localization language schema for game.json",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "description": "Special metadata property for the language",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The language's name shown in the language menu"
        },
        "fallbacks": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "minItems": 0,
          "maxItems": 4,
          "description": "The language codes from which translations can be pulled from if missing keys in this file."
        }
      },
      "required": [
        "name"
      ]
    },
    "formatPercent": {
      "type": "string"
    },
    "startButton": {
      "type": "string"
    },
    "loadButton": {
      "type": "string"
    },
    "optionsButton": {
      "type": "string"
    },
    "quitButton": {
      "type": "string"
    },
    "vSyncButton": {
      "type": "string"
    },
    "cloudsButton": {
      "type": "string"
    },
    "creditsButton": {
      "type": "string"
    },
    "renderDistSlider": {
      "type": "string"
    },
    "invertedMouseButton": {
      "type": "string"
    },
    "mouseSensitivitySlider": {
      "type": "string"
    },
    "soundSlider": {
      "type": "string"
    },
    "musicSlider": {
      "type": "string"
    },
    "fovSlider": {
      "type": "string"
    },
    "musicFreqSlider": {
      "type": "string"
    },
    "maxFPS": {
      "type": "string"
    },
    "maxFPSUnlimited": {
      "type": "string"
    },
    "debugCrashButton": {
      "type": "string"
    },
    "keybindsButton": {
      "type": "string"
    },
    "difficultyButton": {
      "type": "string"
    },
    "difficultyPeaceful": {
      "type": "string"
    },
    "difficultyEasy": {
      "type": "string"
    },
    "difficultyNormal": {
      "type": "string"
    },
    "difficultyHard": {
      "type": "string"
    },
    "languagesButton": {
      "type": "string"
    },
    "rendererButton": {
      "type": "string"
    },
    "rendererNaive": {
      "type": "string"
    },
    "rendererBatched": {
      "type": "string"
    },
    "doneButton": {
      "type": "string"
    },
    "preAlphaText": {
      "type": "string"
    },
    "okButton": {
      "type": "string"
    },
    "Lighting": {
      "type": "string"
    },
    "Respawn": {
      "type": "string"
    },
    "YOU_ARE_DEAD": {
      "type": "string"
    },
    "Return_To_Game": {
      "type": "string"
    },
    "Return_To_Menu": {
      "type": "string"
    },
    "Saving": {
      "type": "string"
    },
    "Dynamic_Sky": {
      "type": "string"
    },
    "Space_Day": {
      "type": "string"
    },
    "Space_Sky": {
      "type": "string"
    },
    "Dark_Night": {
      "type": "string"
    },
    "Earth_Day": {
      "type": "string"
    },
    "Orange_Sky": {
      "type": "string"
    },
    "Pitch_Dark": {
      "type": "string"
    },
    "Overcast": {
      "type": "string"
    },
    "Forward": {
      "type": "string"
    },
    "Backward": {
      "type": "string"
    },
    "Left": {
      "type": "string"
    },
    "Right": {
      "type": "string"
    },
    "Jump": {
      "type": "string"
    },
    "Crouch": {
      "type": "string"
    },
    "Sprint": {
      "type": "string"
    },
    "Prone": {
      "type": "string"
    },
    "Inventory": {
      "type": "string"
    },
    "Cycle_Item_Type": {
      "type": "string"
    },
    "Drop_Item": {
      "type": "string"
    },
    "Hide_UI": {
      "type": "string"
    },
    "Screenshot": {
      "type": "string"
    },
    "Debug_Info": {
      "type": "string"
    },
    "Attack_Break": {
      "type": "string"
    },
    "Pick_Block": {
      "type": "string"
    },
    "Use_Place": {
      "type": "string"
    },
    "Open_Chat": {
      "type": "string"
    },
    "No_Clip": {
      "type": "string"
    },
    "Change_Perspective": {
      "type": "string"
    },
    "Reload_Shaders": {
      "type": "string"
    },
    "Fullscreen": {
      "type": "string"
    },
    "Create_New_World": {
      "type": "string"
    },
    "worldNameButton": {
      "type": "string"
    },
    "defaultWorldName": {
      "type": "string"
    },
    "worldSeedLabel": {
      "type": "string"
    },
    "worldSeedLabel2": {
      "type": "string"
    },
    "worldType": {
      "type": "string"
    },
    "Return_to_Main_Menu": {
      "type": "string"
    },
    "returnButton": {
      "type": "string"
    },
    "Open_Worlds_Directory": {
      "type": "string"
    },
    "YT_Channel": {
      "type": "string"
    },
    "Game_version_prealpha": {
      "type": "string"
    },
    "Game_version_alpha": {
      "type": "string"
    },
    "Game_version_beta": {
      "type": "string"
    },
    "Game_version_release": {
      "type": "string"
    },
    "MAC_warning": {
      "type": "string"
    },
    "Controller": {
      "type": "string"
    },
    "Controllers": {
      "type": "string"
    },
    "Controller_info": {
      "type": "string"
    },
    "on_state": {
      "type": "string"
    },
    "off_state": {
      "type": "string"
    },
    "World_name": {
      "type": "string"
    },
    "Screenshot_info": {
      "type": "string"
    },
    "Screenshot_error": {
      "type": "string"
    },
    "Loading": {
      "type": "string"
    },
    "mouseLeftButton": {
      "type": "string"
    },
    "mouseMiddleButton": {
      "type": "string"
    },
    "mouseRightButton": {
      "type": "string"
    },
    "mouseBackButton": {
      "type": "string"
    },
    "mouseForwardButton": {
      "type": "string"
    },
    "RuntimeException": {
      "type": "string"
    },
    "creditsGameBy": {
      "type": "string"
    },
    "creditsMusic": {
      "type": "string"
    },
    "creditsAdditionalProgramming": {
      "type": "string"
    },
    "creditsAdditionalModelling": {
      "type": "string"
    },
    "creditsAdditionalTexturing": {
      "type": "string"
    },
    "creditsAdditionalMobs": {
      "type": "string"
    },
    "creditsLocalization": {
      "type": "string"
    },
    "multiplayerButton": {
      "type": "string"
    },
    "multiplayerAddressButton": {
      "type": "string"
    },
    "multiplayerJoinButton": {
      "type": "string"
    },
    "multiplayerBadDisconnect": {
      "type": "string"
    },
    "textDisplayInput": {
      "type": "string"
    },
    "skinChangeLabel": {
      "type": "string"
    },
    "skinFileDesc": {
      "type": "string"
    },
    "itemCatalogSearch": {
      "type": "string"
    },
    "boomboxOctave": {
      "type": "string"
    },
    "boomboxPlaySound": {
      "type": "string"
    },
    "worldSelectionSearch": {
      "type": "string"
    },
    "createWorldGamemode": {
      "type": "string"
    },
    "gamemode_survival": {
      "type": "string"
    },
    "gamemode_creative": {
      "type": "string"
    },
    "zone_base:earth": {
      "type": "string"
    },
    "zone_base:flat": {
      "type": "string"
    },
    "zone_base:moon": {
      "type": "string"
    },
    "zone_base:nostalgic_island": {
      "type": "string"
    },
    "zone_base:void": {
      "type": "string"
    },
    "mobUnnamed": {
      "type": "string"
    },
    "zone_base:earth_legacy": {
      "type": "string"
    },
    "comingSoon": {
      "type": "string"
    },
    "langSelectionSearch": {
      "type": "string"
    },
    "worldDescriptionName": {
      "type": "string"
    },
    "worldDescriptionHeader": {
      "type": "string"
    },
    "worldDescriptionGamemode": {
      "type": "string"
    },
    "worldDescriptionGenerator": {
      "type": "string"
    },
    "worldDescriptionDefaultText": {
      "type": "string"
    },
    "worldSelectPlayWorld": {
      "type": "string"
    },
    "worldSelectSaveChanges": {
      "type": "string"
    },
    "loadingAssets": {
      "type": "string"
    },
    "loadingWorld": {
      "type": "string"
    },
    "multiplayerServerName": {
      "type": "string"
    },
    "multiplayerAddServer": {
      "type": "string"
    },
    "multiplayerNewServerDefaultName": {
      "type": "string"
    },
    "multiplayerDeleteServer": {
      "type": "string"
    },
    "multiplayerDeleteConfirmPrompt": {
      "type": "string"
    },
    "multiplayerEditServer": {
      "type": "string"
    },
    "genericSelectionSearch": {
      "type": "string"
    },
    "fullscreenModeButton": {
      "type": "string"
    },
    "fullscreenExclusive": {
      "type": "string"
    },
    "fullscreenBorderless": {
      "type": "string"
    }
  },
  "minProperties": 144
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/id_id/game.json
{
  "$schema": "../game.schema.json",
  "metadata": {
    "name": "Indonesia"
  },
  "formatPercent": "#%",
  "startButton": "Bermain Sendiri",
  "loadButton": "Buka Direktori Penyimpanan",
  "optionsButton": "Opsi",
  "quitButton": "Keluar",
  "vSyncButton": "Vsync: ",
  "creditsButton": "Kredit",
  "renderDistSlider": "Jarak Render: ",
  "invertedMouseButton": "Mouse Terbalik: ",
  "mouseSensitivitySlider": "Sensitivitas Mouse: ",
  "soundSlider": "Suara: ",
  "musicSlider": "Musik: ",
  "fovSlider": "FOV: ",
  "musicFreqSlider": "Kekerapan Musik dalam Menit: ",
  "maxFPS": "FPS Maksimum: ",
  "maxFPSUnlimited": "FPS Maksimum: Tak Terbatas",
  "debugCrashButton": "Debug: Paksa permainan crash",
  "keybindsButton": "Pengaturan Tombol",
  "difficultyButton": "Kesulitan: ",
  "difficultyPeaceful": "Damai",
  "difficultyEasy": "Mudah",
  "difficultyNormal": "Normal",
  "difficultyHard": "Sulit",
  "languagesButton": "Bahasa",
  "rendererButton": "Renderer: ",
  "rendererNaive": "Naive",
  "rendererBatched": "Batched",
  "doneButton": "Selesai",
  "preAlphaText": "Selamat datang di Cosmic Reach! \n Permainan ini masih dalam tahap pengembangan awal, masih kekurangan fitur, belum sepenuhnya selesai, \n dan kemungkinan besar akan memiliki bug, glitch, crash, dan kerusakan dunia permainan.\n Segala hal dapat berubah sewaktu-waktu dan belum mencerminkan versi final permainan ini.\n Permainan ini tersedia untuk kamu mainkan agar kamu dapat memberikan umpan balik untuk membantu memandu pengembangan permainan ini di masa mendatang.\n Selamat mencoba... dan merusak permainan!",
  "okButton": "Ok",
  "Lighting": "Pencahayaan: ",
  "Respawn": "Muncul kembali",
  "YOU_ARE_DEAD": "KAMU TELAH MATI.",
  "Return_To_Game": "Kembali ke Permainan",
  "Return_To_Menu": "Kembali ke Menu",
  "Saving": "Menyimpan...",
  "Dynamic_Sky": "Langit Dinamis",
  "Space_Day": "Siang Antariksa",
  "Space_Sky": "Langit Antariksa",
  "Dark_Night": "Malam Gelap",
  "Earth_Day": "Siang Bumi",
  "Orange_Sky": "Langit Jingga",
  "Pitch_Dark": "Gelap Gulita",
  "Overcast": "Mendung",
  "Forward": "Maju",
  "Backward": "Mundur",
  "Left": "Kiri",
  "Right": "Kanan",
  "Jump": "Lompat",
  "Crouch": "Jongkok",
  "Sprint": "Lari",
  "Prone": "Tengkurap",
  "Inventory": "Persediaan",
  "Cycle_Item_Type": "Ganti Jenis Item",
  "Drop_Item": "Jatuhkan Barang",
  "Hide_UI": "Sembunyikan UI",
  "Screenshot": "Tangkapan Layar",
  "Debug_Info": "Informasi Debug",
  "Attack_Break": "Serang / Hancurkan",
  "Pick_Block": "Pilih Blok",
  "Use_Place": "Gunakan / Tempatkan",
  "Open_Chat": "Buka Obrolan",
  "No_Clip": "No-Clip",
  "Change_Perspective": "Ubah Perspektif",
  "Reload_Shaders": "Muat Ulang Shader",
  "Fullscreen": "Layar Penuh",
  "Create_New_World": "Buat Dunia Baru",
  "worldNameButton": "Nama Dunia: ",
  "defaultWorldName": "Dunia Baru",
  "worldSeedLabel": "Benih Dunia: <Acak>",
  "worldSeedLabel2": "Benih Dunia: ",
  "worldType": "Jenis Dunia: ",
  "Return_to_Main_Menu": "Kembali ke Menu Utama",
  "returnButton": "Kembali",
  "Open_Worlds_Directory": "Buka Direktori Dunia",
  "YT_Channel": "Tonton video devlog di youtube.com/@finalforeach",
  "Game_version_prealpha": "Cosmic Reach Versi Pra-alpha-",
  "Game_version_alpha": "Cosmic Reach Versi Alpha-",
  "Game_version_beta": "Cosmic Reach Versi Beta-",
  "Game_version_release": "Cosmic Reach Versi ",
  "MAC_warning": "PERINGATAN: Mac belum didukung saat ini. Permainan ini kemungkinan besar tidak akan berfungsi.",
  "Controller": "Pengontrol",
  "Controllers": "Beberapa pengontrol",
  "Controller_info": " terdeteksi!\nDukungan pengontrol saat ini belum lengkap,\ndan akan ditingkatkan pada masa mendatang.",
  "on_state": "Hidup",
  "off_state": "Mati",
  "World_name": "Dunia-",
  "Screenshot_info": "Tangkapan layar disimpan ke ",
  "Screenshot_error": "Terjadi kesalahan saat menyimpan tangkapan layar.",
  "Loading": "Memuat",
  "mouseLeftButton": "Tombol Kiri",
  "mouseMiddleButton": "Tombol Tengah",
  "mouseRightButton": "Tombol Kanan",
  "mouseBackButton": "Tombol Belakang",
  "mouseForwardButton": "Tombol Depan",
  "RuntimeException": "Tidak dapat memuat dunia: ",
  "creditsGameBy": "GAME BY:",
  "creditsMusic": "MUSIC:",
  "creditsAdditionalProgramming": "ADDITIONAL PROGRAMMING:",
  "creditsAdditionalModelling": "ADDITIONAL MODELLING:",
  "creditsAdditionalTexturing": "ADDITIONAL TEXTURING:",
  "creditsAdditionalMobs": "ADDITIONAL MOBS:",
  "creditsLocalization": "LOCALIZATION:",
  "multiplayerButton": "Bermain Bersama",
  "multiplayerAddressButton": "Alamat: ",
  "multiplayerJoinButton": "Bergabung",
  "multiplayerBadDisconnect": "Terputus! Alasan:",
  "textDisplayInput": "Ketik di sini...",
  "skinChangeLabel": "Ubah Skin",
  "skinFileDesc": "Berkas PNG dengan ukuran 128x64 piksel",
  "itemCatalogSearch": "Telusuri...",
  "boomboxOctave": "Oktaf",
  "boomboxPlaySound": "Mainkan",
  "worldSelectionSearch": "Telusuri Dunia...",
  "createWorldGamemode": "Mode Permainan:",
  "gamemode_survival": "Sintas",
  "gamemode_creative": "Kreatif",
  "zone_base:earth": "Bumi",
  "zone_base:flat": "Datar",
  "zone_base:moon": "Bulan",
  "zone_base:nostalgic_island": "Pulau-Pulau Nostalgia",
  "zone_base:void": "Dunia Hampa",
  "mobUnnamed": "Tanpa Nama",
  "zone_base:earth_legacy": "Bumi (Lawas)",
  "comingSoon": "Segera hadir...",
  "langSelectionSearch": "Telusuri Bahasa...",
  "worldDescriptionName": "Nama Dunia:",
  "worldDescriptionHeader": "Deskripsi",
  "worldDescriptionGamemode": "Mode Permainan: ",
  "worldDescriptionGenerator": "Jenis Dunia: ",
  "worldDescriptionDefaultText": "Masukkan Deskripsi Dunia...",
  "worldSelectPlayWorld": "Bermain",
  "worldSelectSaveChanges": "Simpan Perubahan",
  "loadingAssets": "Aset",
  "loadingWorld": "Dunia",
  "multiplayerServerName": "Nama Peladen: ",
  "multiplayerAddServer": "Tambah Peladen",
  "multiplayerNewServerDefaultName": "Peladen Baru",
  "multiplayerDeleteServer": "Hapus Peladen",
  "multiplayerDeleteConfirmPrompt": "Apakah kamu yakin ingin menghapus {0}?",
  "multiplayerEditServer": "Sunting Peladen",
  "genericSelectionSearch": "Telusuri..."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/cs_cz/game.json
{
  "$schema": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
  "metadata": {
    "name": "Čeština",
    "fallbacks": [
      "sk_sk",
      "en_us"
    ]
  },
  "formatPercent": "# %",
  "startButton": "Hrát",
  "loadButton": "Otevřít ukládací adresář",
  "optionsButton": "Nastavení",
  "quitButton": "Ukončit",
  "vSyncButton": "Vertikální synchronizace: ",
  "creditsButton": "Zásluhy",
  "renderDistSlider": "Vzdálenost vykreslování: ",
  "invertedMouseButton": "Invertovat myš: ",
  "mouseSensitivitySlider": "Citlivost myši: ",
  "soundSlider": "Zvuk: ",
  "musicSlider": "Hudba: ",
  "musicFreqSlider": "Frekvence hudby v minutách: ",
  "fovSlider": "FOV: ",
  "maxFPS": "Limit FPS: ",
  "maxFPSUnlimited": "Limit FPS: Bez limitu",
  "debugCrashButton": "Debug: Crashnout hru",
  "keybindsButton": "Klávesové zkratky",
  "difficultyButton": "Obtížnost: ",
  "difficultyPeaceful": "mírumilovná",
  "difficultyEasy": "jednoduchá",
  "difficultyNormal": "normální",
  "difficultyHard": "těžká",
  "languagesButton": "Jazyk - Language",
  "rendererButton": "Renderování: ",
  "rendererNaive": "Základní",
  "rendererBatched": "Po částech",
  "doneButton": "Hotovo",
  "preAlphaText": "Vítejte ve hře Cosmic Reach! \n Hra je v ve velmi rané fázi vývoje, chybí jí mnohé funkce a není zdaleka kompletní. \n Hra nejspíše stále obsahuje bugy, glitche a crashe což může vést k poškození světa.\n Všechno se může změnit a nemusí odpovídat konečnému vzhledu hry.\n Je k dispozici pro Vás abyste mohli poskytnout zpětnou vazbu a pomoct řídit budoucnost této hry \n Šťastné testování... a rozbíjení hry!",
  "okButton": "Ok",
  "Lighting": "Osvětlení: ",
  "Respawn": "Respawnout",
  "YOU_ARE_DEAD": "JSTE MTRVÍ.",
  "Return_To_Game": "Zpět do hry",
  "Return_To_Menu": "Zpět do menu",
  "Saving": "Ukládám...",
  "Dynamic_Sky": "Dynamická obloha",
  "Space_Day": "Vesmírný den",
  "Dark_Night": "Temná noc",
  "Earth_Day": "Pozemský den",
  "Orange_Sky": "Oranžová obloha",
  "Pitch_Dark": "Úplná tma",
  "Overcast": "Zataženo",
  "Forward": "Dopředu",
  "Backward": "Dozadu",
  "Left": "Doleva",
  "Right": "Doprava",
  "Jump": "Skočit",
  "Crouch": "Přikrčit se",
  "Sprint": "Sprintovat",
  "Prone": "Lehnout si",
  "Inventory": "Inventář",
  "Cycle_Item_Type": "Cyklicky měnit typ předmětu",
  "Drop_Item": "Zahodit předmet",
  "Hide_UI": "Skrýt UI",
  "Screenshot": "Snímek obrazovky",
  "Debug_Info": "Debugovací informace",
  "Attack_Break": "Útok/ničení",
  "Pick_Block": "Vzít blok",
  "Use_Place": "Položit blok",
  "Open_Chat": "Otevřít chat",
  "No_Clip": "Spectator",
  "Change_Perspective": "Změnit perspektivu",
  "Reload_Shaders": "Znovu načíst shadery",
  "Fullscreen": "Na celou obrazovku",
  "Create_New_World": "Vytvořit nový svět",
  "worldNameButton": "Název světa: ",
  "defaultWorldName": "Nový Svět",
  "worldSeedLabel": "Seed světa: <náhodný>",
  "worldSeedLabel2": "Seed světa: ",
  "worldType": "Typ světa: ",
  "Return_to_Main_Menu": "Zpět do hlavního menu",
  "returnButton": "Zpět",
  "Open_Worlds_Directory": "Otevřít adresář světů",
  "YT_Channel": "Sleduj změny na youtube.com/@finalforeach",
  "Game_version_prealpha": "Cosmic Reach verze Pre-alpha-",
  "Game_version_alpha": "Cosmic Reach verze Alpha-",
  "Game_version_beta": "Cosmic Reach verze Beta-",
  "Game_version_release": "Cosmic Reach verze ",
  "MAC_warning": "UPOZORNĚNÍ: Mac není zatím podporován. Hra nejspíše nebude fungovat.",
  "Controller": "Ovladač detekován",
  "Controllers": "Ovladače detekovány",
  "Controller_info": "!\nPodpora ovladačů není ještě dokončená,\na bude vylepšena v budoucích updatech.",
  "on_state": "Zapnuto",
  "off_state": "Vypnuto",
  "World_name": "Svět-",
  "Screenshot_info": "Snímek obrazovky uložen do ",
  "Screenshot_error": "Nastala chyba při ukládáni snímku obrazovky.",
  "Loading": "Načítám",
  "mouseLeftButton": "Levé tlačítko",
  "mouseMiddleButton": "Střední tlačítko",
  "mouseRightButton": "Pravé tlačítko",
  "mouseBackButton": "Tlačítko dozadu",
  "mouseForwardButton": "Tlačítko dopředu",
  "RuntimeException": "Svět se nepovedlo načíst: ",
  "creditsGameBy": "AUTOR HRY:",
  "creditsMusic": "HUDBA:",
  "creditsAdditionalProgramming": "DALŠÍ PROGRAMOVÁNÍ:",
  "creditsAdditionalModelling": "DALŠÍ MODELOVÁNÍ:",
  "creditsAdditionalTexturing": "DALŠÍ GRAFIKA:",
  "creditsAdditionalMobs": "DALŠÍ MOBOVÉ:",
  "creditsLocalization": "LOKALIZACE:",
  "multiplayerButton": "Multiplayer",
  "multiplayerAddressButton": "Adresa serveru: ",
  "multiplayerJoinButton": "Připojit",
  "multiplayerBadDisconnect": "Byli jste odpojeni. Důvod:",
  "textDisplayInput": "Pište zde...",
  "skinChangeLabel": "Změnit skin",
  "skinFileDesc": "Soubor typu PNG se 128x64 pixely",
  "itemCatalogSearch": "Hledat...",
  "boomboxOctave": "Oktáva",
  "boomboxPlaySound": "Přehrát",
  "worldSelectionSearch": "Vyhledat Světy...",
  "createWorldGamemode": "Herní režim:",
  "gamemode_survival": "Přežití",
  "gamemode_creative": "Tvoření",
  "zone_base:earth": "Země",
  "zone_base:flat": "Placka",
  "zone_base:moon": "Měsíc",
  "zone_base:nostalgic_island": "Nostalgické Ostrovy",
  "zone_base:void": "Prázdný Svět",
  "mobUnnamed": "Nepojmenovaný",
  "zone_base:earth_legacy": "Země (Stará)"
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/hu_hu/game.json
{
  "$schema": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
  "metadata":
  {
    "name": "Magyar"
  },
  "formatPercent": "#%",
  "startButton": "Indítás",
  "loadButton": "Mentési mappa megnyitása",
  "optionsButton": "Beállítások",
  "quitButton": "Kilépés",
  "vSyncButton": "Vsync: ",
  "creditsButton": "Stáblista",
  "renderDistSlider": "Renderelési távolság: ",
  "invertedMouseButton": "Fordított egér: ",
  "mouseSensitivitySlider": "Egér érzékenység: ",
  "soundSlider": "Hang: ",
  "musicSlider": "Zene: ",
  "musicFreqSlider": "Zene frekvencia percekben: ",
  "fovSlider": "FOV: ",
  "maxFPS": "Max FPS: ",
  "maxFPSUnlimited": "Max FPS: Korlátlan",
  "debugCrashButton": "Hibakeresés: Játék összeomlasztása",
  "keybindsButton": "Irányítás",
  "difficultyButton": "Nehézség: ",
  "difficultyPeaceful": "Békés",
  "difficultyEasy": "Könnyű",
  "difficultyNormal": "Normál",
  "difficultyHard": "Nehéz",
  "languagesButton": "Nyelv",
  "rendererButton": "Renderelő: ",
  "rendererNaive": "Naiv",
  "rendererBatched": "Kötegelt",
  "doneButton": "Kész",
  "preAlphaText": "Üdvözöllek a Cosmic Reach-ben! \n A játék nagyon korai fejlesztési szakaszban van, hiányoznak funkciók, messze nincs kész \n és valószínűleg lesznek hibák, zavarok, összeomlások és világ korruptálódások.\n Minden változás alatt áll és nem képviseli a végső játékot.\n Elérhető, hogy játszhass vele, és visszajelzést adhass a játék jövőjének segítéséhez \n Jó szórakozást a teszteléshez... és játék-törést!",
  "okButton": "Oké",
  "Lighting": "Világítás: ",
  "Respawn": "Újraéledés",
  "YOU_ARE_DEAD": "MEGHALTÁL.",
  "Return_To_Game": "Vissza a játékba",
  "Return_To_Menu": "Vissza a menübe",
  "Saving": "Mentés...",
  "Dynamic_Sky": "Dinamikus ég",
  "Space_Day": "Űr nap",
  "Dark_Night": "Sötét éjszaka",
  "Earth_Day": "Föld nap",
  "Orange_Sky": "Narancssárga ég",
  "Pitch_Dark": "Koromsötét",
  "Overcast": "Felhős",
  "Forward": "Előre",
  "Backward": "Hátra",
  "Left": "Balra",
  "Right": "Jobbra",
  "Jump": "Ugrás",
  "Crouch": "Guggolás",
  "Sprint": "Sprintelés",
  "Prone": "Fekvés",
  "Inventory": "Eszköztár",
  "Cycle_Item_Type": "Tárgy típus váltás",
  "Drop_Item": "Tárgy elhajítása",
  "Hide_UI": "UI elrejtése",
  "Screenshot": "Képernyőkép",
  "Debug_Info": "Hibakeresési infó",
  "Attack_Break": "Támadás / Törés",
  "Pick_Block": "Blokk felszedése",
  "Use_Place": "Használ / Elhelyez",
  "Open_Chat": "Chat megnyitása",
  "No_Clip": "No-Clip",
  "Change_Perspective": "Perspektívaváltás",
  "Reload_Shaders": "Shaderek újratöltése",
  "Fullscreen": "Teljes képernyő",
  "Create_New_World": "Új világ létrehozása",
  "worldNameButton": "Világ neve: ",
  "defaultWorldName": "Új világ",
  "worldSeedLabel": "Világ mag: <Véletlenszerű>",
  "worldSeedLabel2": "Világ mag: ",
  "worldType": "Világ típusa: ",
  "Return_to_Main_Menu": "Vissza a főmenübe",
  "returnButton": "Vissza",
  "Open_Worlds_Directory": "Világok mappa megnyitása",
  "YT_Channel": "Nézd meg a fejlesztői naplókat a youtube.com/@finalforeach oldalon",
  "Game_version_prealpha": "Cosmic Reach Verzió Pre-alpha-",
  "Game_version_alpha": "Cosmic Reach Verzió Alpha-",
  "Game_version_beta": "Cosmic Reach Verzió Beta-",
  "Game_version_release": "Cosmic Reach Verzió ",
  "MAC_warning": "FIGYELEM: A Mac jelenleg nem támogatott. Valószínű, hogy a játék nem fog működni.",
  "Controller": "Kontroller",
  "Controllers": "Kontrollerek",
  "Controller_info": " érzékelve!\nA kontroller támogatás jelenleg hiányos\nés a későbbi frissítésekben javításra kerül.",
  "on_state": "Be",
  "off_state": "Ki",
  "World_name": "Világ-",
  "Screenshot_info": "Képernyőkép mentve ide: ",
  "Screenshot_error": "Hiba képernyőkép mentésekor.",
  "Loading": "Betöltés",
  "mouseLeftButton" : "Bal gomb",
  "mouseMiddleButton" : "Középső gomb",
  "mouseRightButton" : "Jobb gomb",
  "mouseBackButton" : "Vissza gomb",
  "mouseForwardButton" : "Előre gomb",
  "RuntimeException": "Nem sikerült betölteni a világot: ",
  "creditsGameBy": "JÁTÉK TŐLE:",
  "creditsMusic": "ZENE:",
  "creditsAdditionalProgramming": "TOVÁBBI PROGRAMOZÁS:",
  "creditsAdditionalModelling": "TOVÁBBI MODELLEZÉS:",
  "creditsAdditionalTexturing": "TOVÁBBI TEXTÚRÁLÁS:",
  "creditsAdditionalMobs": "TOVÁBBI MOBOK:",
  "creditsLocalization": "LOKALIZÁCIÓ:",
  "multiplayerButton": "Többjátékos mód",
  "multiplayerAddressButton": "Cím: ",
  "multiplayerJoinButton": "Csatlakozás",
  "multiplayerBadDisconnect": "Lecsatlakozva! Indok:",
  "textDisplayInput": "Írj ide...",
  "skinChangeLabel": "Válts kínézetet",
  "skinFileDesc": "PNG fájl 128x64 pixellel",
  "itemCatalogSearch": "Keresés...",
  "boomboxOctave": "Oktáv",
  "boomboxPlaySound": "Lejátszás",
  "worldSelectionSearch": "Világok keresése...",
  "createWorldGamemode": "Játékmód:",
  "gamemode_survival": "Túlélő",
  "gamemode_creative": "Kreatív",
  "zone_base:earth": "Föld",
  "zone_base:flat": "Lapos",
  "zone_base:moon": "Hold",
  "zone_base:nostalgic_island": "Nosztalgikus szigetek",
  "zone_base:void": "Üres világ",
  "mobUnnamed": "Névtelen",
  "zone_base:earth_legacy": "Föld (Régi)",
  "comingSoon": "Hamarosan...",
  "langSelectionSearch": "Nyelvek keresése...",
  "worldDescriptionName": "Világ neve:",
  "worldDescriptionHeader": "Leírás",
  "worldDescriptionGamemode": "Játékmód: ",
  "worldDescriptionGenerator": "Világ típusa: ",
  "worldDescriptionDefaultText": "Világ leírás megadása...",
  "worldSelectPlayWorld": "Játék",
  "worldSelectSaveChanges": "Változtatások mentése"
}
