=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/game.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
  "title": "Cosmic Reach language (game.json)",
  "description": "FinalForEach's Cosmic Reach game localization language schema for game.json",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "description": "Special metadata property for the language",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The language's name shown in the language menu"
        },
        "fallbacks": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "minItems": 0,
          "maxItems": 4,
          "description": "The language codes from which translations can be pulled from if missing keys in this file."
        }
      },
      "required": [
        "name"
      ]
    },
    "formatPercent": {
      "type": "string"
    },
    "startButton": {
      "type": "string"
    },
    "loadButton": {
      "type": "string"
    },
    "optionsButton": {
      "type": "string"
    },
    "quitButton": {
      "type": "string"
    },
    "vSyncButton": {
      "type": "string"
    },
    "cloudsButton": {
      "type": "string"
    },
    "creditsButton": {
      "type": "string"
    },
    "renderDistSlider": {
      "type": "string"
    },
    "invertedMouseButton": {
      "type": "string"
    },
    "mouseSensitivitySlider": {
      "type": "string"
    },
    "soundSlider": {
      "type": "string"
    },
    "musicSlider": {
      "type": "string"
    },
    "fovSlider": {
      "type": "string"
    },
    "musicFreqSlider": {
      "type": "string"
    },
    "maxFPS": {
      "type": "string"
    },
    "maxFPSUnlimited": {
      "type": "string"
    },
    "debugCrashButton": {
      "type": "string"
    },
    "keybindsButton": {
      "type": "string"
    },
    "difficultyButton": {
      "type": "string"
    },
    "difficultyPeaceful": {
      "type": "string"
    },
    "difficultyEasy": {
      "type": "string"
    },
    "difficultyNormal": {
      "type": "string"
    },
    "difficultyHard": {
      "type": "string"
    },
    "languagesButton": {
      "type": "string"
    },
    "rendererButton": {
      "type": "string"
    },
    "rendererNaive": {
      "type": "string"
    },
    "rendererBatched": {
      "type": "string"
    },
    "doneButton": {
      "type": "string"
    },
    "preAlphaText": {
      "type": "string"
    },
    "okButton": {
      "type": "string"
    },
    "Lighting": {
      "type": "string"
    },
    "Respawn": {
      "type": "string"
    },
    "YOU_ARE_DEAD": {
      "type": "string"
    },
    "Return_To_Game": {
      "type": "string"
    },
    "Return_To_Menu": {
      "type": "string"
    },
    "Saving": {
      "type": "string"
    },
    "Dynamic_Sky": {
      "type": "string"
    },
    "Space_Day": {
      "type": "string"
    },
    "Space_Sky": {
      "type": "string"
    },
    "Dark_Night": {
      "type": "string"
    },
    "Earth_Day": {
      "type": "string"
    },
    "Orange_Sky": {
      "type": "string"
    },
    "Pitch_Dark": {
      "type": "string"
    },
    "Overcast": {
      "type": "string"
    },
    "Forward": {
      "type": "string"
    },
    "Backward": {
      "type": "string"
    },
    "Left": {
      "type": "string"
    },
    "Right": {
      "type": "string"
    },
    "Jump": {
      "type": "string"
    },
    "Crouch": {
      "type": "string"
    },
    "Sprint": {
      "type": "string"
    },
    "Prone": {
      "type": "string"
    },
    "Inventory": {
      "type": "string"
    },
    "Cycle_Item_Type": {
      "type": "string"
    },
    "Drop_Item": {
      "type": "string"
    },
    "Hide_UI": {
      "type": "string"
    },
    "Screenshot": {
      "type": "string"
    },
    "Debug_Info": {
      "type": "string"
    },
    "Attack_Break": {
      "type": "string"
    },
    "Pick_Block": {
      "type": "string"
    },
    "Use_Place": {
      "type": "string"
    },
    "Open_Chat": {
      "type": "string"
    },
    "No_Clip": {
      "type": "string"
    },
    "Change_Perspective": {
      "type": "string"
    },
    "Reload_Shaders": {
      "type": "string"
    },
    "Fullscreen": {
      "type": "string"
    },
    "Create_New_World": {
      "type": "string"
    },
    "worldNameButton": {
      "type": "string"
    },
    "defaultWorldName": {
      "type": "string"
    },
    "worldSeedLabel": {
      "type": "string"
    },
    "worldSeedLabel2": {
      "type": "string"
    },
    "worldType": {
      "type": "string"
    },
    "Return_to_Main_Menu": {
      "type": "string"
    },
    "returnButton": {
      "type": "string"
    },
    "Open_Worlds_Directory": {
      "type": "string"
    },
    "YT_Channel": {
      "type": "string"
    },
    "Game_version_prealpha": {
      "type": "string"
    },
    "Game_version_alpha": {
      "type": "string"
    },
    "Game_version_beta": {
      "type": "string"
    },
    "Game_version_release": {
      "type": "string"
    },
    "MAC_warning": {
      "type": "string"
    },
    "Controller": {
      "type": "string"
    },
    "Controllers": {
      "type": "string"
    },
    "Controller_info": {
      "type": "string"
    },
    "on_state": {
      "type": "string"
    },
    "off_state": {
      "type": "string"
    },
    "World_name": {
      "type": "string"
    },
    "Screenshot_info": {
      "type": "string"
    },
    "Screenshot_error": {
      "type": "string"
    },
    "Loading": {
      "type": "string"
    },
    "mouseLeftButton": {
      "type": "string"
    },
    "mouseMiddleButton": {
      "type": "string"
    },
    "mouseRightButton": {
      "type": "string"
    },
    "mouseBackButton": {
      "type": "string"
    },
    "mouseForwardButton": {
      "type": "string"
    },
    "RuntimeException": {
      "type": "string"
    },
    "creditsGameBy": {
      "type": "string"
    },
    "creditsMusic": {
      "type": "string"
    },
    "creditsAdditionalProgramming": {
      "type": "string"
    },
    "creditsAdditionalModelling": {
      "type": "string"
    },
    "creditsAdditionalTexturing": {
      "type": "string"
    },
    "creditsAdditionalMobs": {
      "type": "string"
    },
    "creditsLocalization": {
      "type": "string"
    },
    "multiplayerButton": {
      "type": "string"
    },
    "multiplayerAddressButton": {
      "type": "string"
    },
    "multiplayerJoinButton": {
      "type": "string"
    },
    "multiplayerBadDisconnect": {
      "type": "string"
    },
    "textDisplayInput": {
      "type": "string"
    },
    "skinChangeLabel": {
      "type": "string"
    },
    "skinFileDesc": {
      "type": "string"
    },
    "itemCatalogSearch": {
      "type": "string"
    },
    "boomboxOctave": {
      "type": "string"
    },
    "boomboxPlaySound": {
      "type": "string"
    },
    "worldSelectionSearch": {
      "type": "string"
    },
    "createWorldGamemode": {
      "type": "string"
    },
    "gamemode_survival": {
      "type": "string"
    },
    "gamemode_creative": {
      "type": "string"
    },
    "zone_base:earth": {
      "type": "string"
    },
    "zone_base:flat": {
      "type": "string"
    },
    "zone_base:moon": {
      "type": "string"
    },
    "zone_base:nostalgic_island": {
      "type": "string"
    },
    "zone_base:void": {
      "type": "string"
    },
    "mobUnnamed": {
      "type": "string"
    },
    "zone_base:earth_legacy": {
      "type": "string"
    },
    "comingSoon": {
      "type": "string"
    },
    "langSelectionSearch": {
      "type": "string"
    },
    "worldDescriptionName": {
      "type": "string"
    },
    "worldDescriptionHeader": {
      "type": "string"
    },
    "worldDescriptionGamemode": {
      "type": "string"
    },
    "worldDescriptionGenerator": {
      "type": "string"
    },
    "worldDescriptionDefaultText": {
      "type": "string"
    },
    "worldSelectPlayWorld": {
      "type": "string"
    },
    "worldSelectSaveChanges": {
      "type": "string"
    },
    "loadingAssets": {
      "type": "string"
    },
    "loadingWorld": {
      "type": "string"
    },
    "multiplayerServerName": {
      "type": "string"
    },
    "multiplayerAddServer": {
      "type": "string"
    },
    "multiplayerNewServerDefaultName": {
      "type": "string"
    },
    "multiplayerDeleteServer": {
      "type": "string"
    },
    "multiplayerDeleteConfirmPrompt": {
      "type": "string"
    },
    "multiplayerEditServer": {
      "type": "string"
    },
    "genericSelectionSearch": {
      "type": "string"
    },
    "fullscreenModeButton": {
      "type": "string"
    },
    "fullscreenExclusive": {
      "type": "string"
    },
    "fullscreenBorderless": {
      "type": "string"
    }
  },
  "minProperties": 144
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/tr_tr/game.json
{
  "$schema": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
  "metadata":
  {
    "name": "Türkçe"
  },
  "formatPercent": "%#",
  "startButton": "Başlat",
  "loadButton": "Kayıt Klasörünü Aç",
  "optionsButton": "Ayarlar",
  "quitButton": "Çıkış",
  "vSyncButton": "Dikey Senkronizasyon: ",
  "creditsButton": "Katkıda Bulunanlar",
  "renderDistSlider": "Görüş Mesafesi: ",
  "invertedMouseButton": "Fare Kontrollerini Tersine Çevir: ",
  "mouseSensitivitySlider": "Fare Hassasiyeti: ",
  "soundSlider": "Ses Düzeyi: ",
  "musicSlider": "Müzik: ",
  "musicFreqSlider": "Dakikadaki Müzik Sıklığı: ",
  "fovSlider": "Görüş Açısı: ",
  "maxFPS": "Maksimum Kare Sayısı: ",
  "maxFPSUnlimited": "Maksimum Kare Sayısı: Sınırsız",
  "debugCrashButton": "Hata Ayıklama: Oyunu çökert",
  "keybindsButton": "Tuş Atamaları",
  "difficultyButton": "Zorluk: ",
  "difficultyPeaceful": "Barışçıl",
  "difficultyEasy": "Kolay",
  "difficultyNormal": "Normal",
  "difficultyHard": "Zor",
  "languagesButton": "Dil",
  "rendererButton": "Görüntü işleyici: ",
  "rendererNaive": "Basit",
  "rendererBatched": "Gruplu",
  "doneButton": "Bitti",
  "preAlphaText": "Cosmic Reach'e Hoş Geldin! \n Oyun oldukça erken bir geliştirme aşamasında, eksik özellikleri var, bitmeye yakın bile değil. \n Muhtemelen Buglarla, Hatalarla, çökmelerle ve dünya bozulmalarla karşılaşacaksın. \n Her şey değişikliğe tabidir ve nihai oyunu temsil etmemektedir.\n Bu oyun, geri bildirim vererek oyunun geleceğini şekillendirmeye yardımcı olabilmeniz için oynanabilir durumda. \n Keyifli testler... ve oyunu bozmayı da unutma!",
  "okButton": "Tamam",
  "Lighting": "Aydınlatma: ",
  "Respawn": "Yeniden Canlan",
  "YOU_ARE_DEAD": "ÖLDÜN",
  "Return_To_Game": "Oyuna Dön",
  "Return_To_Menu": "Ana Menüye Dön",
  "Saving": "Kaydediliyor...",
  "Dynamic_Sky": "Dinamik Gökyüzü",
  "Space_Day": "Uzay Gündüzü",
  "Dark_Night": "Karanlık Gece",
  "Earth_Day": "Dünya Gündüzü",
  "Orange_Sky": "Turuncu Gökyüzü",
  "Pitch_Dark": "Zifiri Karanlık",
  "Overcast": "Bulutlu",
  "Forward": "İleri",
  "Backward": "Geri",
  "Left": "Sol",
  "Right": "Sağ",
  "Jump": "Zıpla",
  "Crouch": "Eğil",
  "Sprint": "Koş",
  "Prone": "Sürün",
  "Inventory": "Envanter",
  "Drop_Item": "Eşyayı Bırak",
  "Cycle_Item_Type": "Döngü Eşya Türü",
  "Hide_UI": "Arayüzü Gizle",
  "Screenshot": "Ekran Görüntüsü",
  "Debug_Info": "Hata Ayıklama Bilgisi",
  "Attack_Break": "Saldır / Kır",
  "Pick_Block": "Blok Seç",
  "Use_Place": "Kullan / Yerleştir",
  "Open_Chat": "Sohbeti Aç",
  "No_Clip": "Duvardan Geçme",
  "Change_Perspective": "Perspektifi Değiştir",
  "Reload_Shaders": "Gölgelendirmeleri Yenile",
  "Fullscreen": "Tam Ekran",
  "Create_New_World": "Yeni Dünya Oluştur",
  "worldNameButton": "Dünya Adı: ",
  "defaultWorldName": "Yeni Dünya",
  "worldSeedLabel": "Dünya tohumu: <Rastgele>",
  "worldSeedLabel2": "Dünya tohumu: ",
  "worldType": "Dünya Tipi: ",
  "Return_to_Main_Menu": "Ana Menüye Dön",
  "returnButton": "Geri",
  "Open_Worlds_Directory": "Dünyaların Klasörünü Aç",
  "YT_Channel": "Geliştirme günlüklerini youtube.com/@finalforeach adresinden izleyebilirsin",
  "Game_version_prealpha": "Cosmic Reach Sürüm Pre-alpha-",
  "Game_version_alpha": "Cosmic Reach Sürüm Alpha-",
  "Game_version_beta": "Cosmic Reach Sürüm Beta-",
  "Game_version_release": "Cosmic Reach Sürüm ",
  "MAC_warning": "UYARI: Mac şu anda desteklenmemektedir. Oyunun Mac'te çalışması mümkün değildir.",
  "Controller": "Kontrolcü",
  "Controllers": "Kontrolcüler",
  "Controller_info": " algılandı!\nKontrolcü desteği şu anda tamamlanmamıştır,\n ve ilerleyen güncellemelerde geliştirilecektir..",
  "on_state": "Açık",
  "off_state": "Kapalı",
  "World_name": "Dünya-",
  "Screenshot_info": "Ekran görüntüsü şuraya kaydedildi: ",
  "Screenshot_error": "Ekran görüntüsü kaydedilirken bir hata oluştu.",
  "Loading": "Yükleniyor",
  "mouseLeftButton" : "Sol Düğme",
  "mouseMiddleButton" : "Orta Düğme",
  "mouseRightButton" : "Sağ Düğme",
  "mouseBackButton" : "Geri Düğmesi",
  "mouseForwardButton" : "İleri Düğmesi",
  "RuntimeException": "Şu dünya yüklenemiyor: ",
  "creditsGameBy": "OYUN YAPIMCISI:",
  "creditsMusic": "MÜZİK:",
  "creditsAdditionalProgramming": "İLAVE PROGRAMLAMA:",
  "creditsAdditionalModelling": "İLAVE MODELLEME:",
  "creditsAdditionalTexturing": "İLAVE DOKULANDIRMA:",
  "creditsAdditionalMobs": "EK YARATIKLAR:",
  "creditsLocalization": "YERELLEŞTİRME:",
  "multiplayerButton": "Çok Oyunculu",
  "multiplayerAddressButton": "Adres: ",
  "multiplayerJoinButton": "Katıl",
  "multiplayerBadDisconnect": "Bağlantı kesildi! Sebep:",
  "textDisplayInput": "Buraya yaz...",
  "skinChangeLabel": "Skin Değiştir",
  "skinFileDesc": "128'e 64 Pixel PNG dosyası",
  "itemCatalogSearch": "Ara...",
  "boomboxOctave": "Oktav",
  "boomboxPlaySound": "Oynat",
  "worldSelectionSearch": "Dünya Ara...",
  "createWorldGamemode": "Oyun Modu:",
  "gamemode_survival": "Hayatta Kalma",
  "gamemode_creative": "Yaratıcı",
  "zone_base:earth": "Dünya",
  "zone_base:flat": "Düzlük",
  "zone_base:moon": "Ay",
  "zone_base:nostalgic_island": "Nostalji Adaları",
  "zone_base:void": "Boşluk Dünyası",
  "mobUnnamed": "Adsız",
  "zone_base:earth_legacy": "Dünya (Eski)",
  "comingSoon": "Çok Yakında...",
  "langSelectionSearch": "Dil Ara...",
  "worldDescriptionName": "Dünya Adı:",
  "worldDescriptionHeader": "Açıklama",
  "worldDescriptionGamemode": "Oyun Modu: ",
  "worldDescriptionGenerator": "Dünya Tipi: ",
  "worldDescriptionDefaultText": "Dünya Açıklaması Girin...",
  "worldSelectPlayWorld": "Oyna",
  "worldSelectSaveChanges": "Değişiklikleri Kaydet",
  "loadingAssets": "Kaynaklar",
  "loadingWorld": "Dünya",
  "multiplayerServerName": "Sunucu İsmi: ",
  "multiplayerAddServer": "Dunucu Ekle",
  "multiplayerNewServerDefaultName": "Yeni Sunucu",
  "multiplayerDeleteServer": "Sunucuyu Sil",
  "multiplayerDeleteConfirmPrompt": "{0}'yı silmek istediğinize emin misiniz?",
  "multiplayerEditServer": "Sunucuyu Düzenle",
  "genericSelectionSearch": "Ara..."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/en_gb/game.json
{
  "$schema": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
  "metadata":
  {
    "name": "English (United Kingdom)"
  },
  "formatPercent": "#%",
  "startButton": "Start",
  "loadButton": "Open Save Directory",
  "optionsButton": "Options",
  "quitButton": "Quit",
  "vSyncButton": "Vsync: ",
  "cloudsButton": "Clouds: ",
  "creditsButton": "Credits",
  "renderDistSlider": "Render Distance: ",
  "invertedMouseButton": "Inverted Mouse: ",
  "mouseSensitivitySlider": "Mouse Sensitivity: ",
  "soundSlider": "Sound: ",
  "musicSlider": "Music: ",
  "fovSlider": "FOV: ",
  "maxFPS": "Max FPS: ",
  "maxFPSUnlimited": "Max FPS: Unlimited",
  "debugCrashButton": "Debug: Crash the game",
  "keybindsButton": "Keybinds",
  "difficultyButton": "Difficulty: ",
  "difficultyPeaceful": "Peaceful",
  "difficultyEasy": "Easy",
  "difficultyNormal": "Normal",
  "difficultyHard": "Hard",
  "languagesButton": "Language",
  "rendererButton": "Renderer: ",
  "rendererNaive": "Naive",
  "rendererBatched": "Batched",
  "doneButton": "Done",
  "preAlphaText": "Welcome to Cosmic Reach! \n The game is in very early development, it is missing features, is nowhere near complete, \n and will likely have bugs, glitches, crashes and world corruption.\n Everything is subject to change and is not representative of the final game.\n It's available for you to play so that you can give feedback to help guide the future of this game \n Happy testing... and game-breaking!",
  "okButton": "Ok",
  "Lighting": "Lighting: ",
  "Respawn": "Respawn",
  "YOU_ARE_DEAD": "YOU ARE DEAD.",
  "Return_To_Game": "Return To Game",
  "Return_To_Menu": "Return To Menu",
  "Saving": "Saving...",
  "Dynamic_Sky": "Dynamic Sky",
  "Space_Day": "Space Day",
  "Dark_Night": "Dark Night",
  "Earth_Day": "Earth Day",
  "Orange_Sky": "Orange Sky",
  "Pitch_Dark": "Pitch Dark",
  "Overcast": "Overcast",
  "Forward": "Forward",
  "Backward": "Backward",
  "Left": "Left",
  "Right": "Right",
  "Jump": "Jump",
  "Crouch": "Crouch",
  "Sprint": "Sprint",
  "Prone": "Prone",
  "Inventory": "Inventory",
  "Cycle_Item_Type": "Cycle Item Type",
  "Drop_Item": "Drop Item",
  "Hide_UI": "Hide UI",
  "Screenshot": "Screenshot",
  "Debug_Info": "Debug Info",
  "Attack_Break": "Attack / Break",
  "Pick_Block": "Pick Block",
  "Use_Place": "Use / Place",
  "Open_Chat": "Open Chat",
  "No_Clip": "No-Clip",
  "Reload_Shaders": "Reload Shaders",
  "Fullscreen": "Fullscreen",
  "Create_New_World": "Create New World",
  "worldNameButton": "World name: ",
  "defaultWorldName": "New World",
  "worldSeedLabel": "World seed: <Random>",
  "worldSeedLabel2": "World seed: ",
  "worldType": "World Type: ",
  "Return_to_Main_Menu": "Return to Main Menu",
  "returnButton": "Back",
  "Open_Worlds_Directory": "Open Worlds Directory",
  "YT_Channel": "Watch the devlogs at youtube.com/@finalforeach",
  "Game_version_prealpha": "Cosmic Reach Version Pre-alpha-",
  "Game_version_alpha": "Cosmic Reach Version Alpha-",
  "Game_version_beta": "Cosmic Reach Version Beta-",
  "Game_version_release": "Cosmic Reach Version ",
  "MAC_warning": "WARNING: Mac is not supported at this time. The game is unlikely to work.",
  "Controller": "Controller",
  "Controllers": "Controllers",
  "Controller_info": " detected!\nController support is incomplete now,\nand will be improved in later updates.",
  "on_state": "On",
  "off_state": "Off",
  "World_name": "World-",
  "Screenshot_info": "Saved screenshot to ",
  "Screenshot_error": "Error saving screenshot.",
  "Loading": "Loading",
  "mouseLeftButton" : "Left Button",
  "mouseMiddleButton" : "Middle Button",
  "mouseRightButton" : "Right Button",
  "mouseBackButton" : "Back Button",
  "mouseForwardButton" : "Forward Button",
  "RuntimeException": "Could not load world: ",
  "creditsGameBy": "GAME BY:",
  "creditsMusic": "MUSIC:",
  "creditsAdditionalProgramming": "ADDITIONAL PROGRAMMING:",
  "creditsAdditionalModelling": "ADDITIONAL MODELLING:",
  "creditsAdditionalTexturing": "ADDITIONAL TEXTURING:",
  "creditsLocalization": "LOCALIZATION:",
  "multiplayerButton": "Multiplayer",
  "multiplayerAddressButton": "Address: ",
  "multiplayerJoinButton": "Join",
  "multiplayerBadDisconnect": "Disconnected! Reason:",
  "textDisplayInput": "Type here..."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/ko_kr/game.json
{
    "metadata": {
        "name": "한국어"
    },
    "formatPercent": "#%",
    "startButton": "싱글 플레이어",
    "loadButton": "세이브 데이터",
    "optionsButton": "옵션",
    "quitButton": "종료",
    "vSyncButton": "Vsync",
    "creditsButton": "크레딧",
    "renderDistSlider": "렌더 거리: ",
    "invertedMouseButton": "마우스 반전: ",
    "mouseSensitivitySlider": "마우스 감도: ",
    "soundSlider": "소리: ",
    "musicSlider": "BGM: ",
    "fovSlider": "FOV: ",
    "musicFreqSlider": "BGM 빈도: ",
    "maxFPS": "최대 FPS: ",
    "maxFPSUnlimited": "최대 FPS: 제한 없음",
    "debugCrashButton": "디버그: ",
    "keybindsButton": "조작키",
    "difficultyButton": "난이도: ",
    "difficultyPeaceful": "평화로움",
    "difficultyEasy": "쉬움",
    "difficultyNormal": "보통",
    "difficultyHard": "어려움",
    "languagesButton": "언어",
    "rendererButton": "렌더러: ",
    "rendererNaive": "단순/직접 처리",
    "rendererBatched": "일괄 처리",
    "doneButton": "완료",
    "preAlphaText": "코스믹 리치에 오신 것을 환영합니다! \n 이 게임은 개발 초기 단계에 있으며, 기능이 부족하고 완성도가 떨어집니다, \n 그리고 버그, 결함, 충돌 및 세계 붕괴가 발생할 가능성이 높습니다. \n 모든 요소는 변경될 수 있으며 최종 게임과 달라질 수 있습니다. \n 이 게임을 플레이하여 도움이 되는 피드백을 제공할 수 있습니다 \n 행복한 테스트 되세요!",
    "okButton": "확인",
    "Lighting": "밝기: ",
    "Respawn": "리스폰",
    "YOU_ARE_DEAD": "당신은 죽었습니다.",
    "Return_To_Game": "게임으로 돌아가기",
    "Return_To_Menu": "메뉴로 돌아가기",
    "Saving": "저장중...",
    "Dynamic_Sky": "다이나믹 스카이",
    "Space_Day": "스페이스 데이",
    "Dark_Night": "다크 나이트",
    "Earth_Day": "어스 데이",
    "Orange_Sky": "오렌지 스카이",
    "Pitch_Dark": "피치 다크",
    "Overcast": "오버캐스트",
    "Forward": "전진",
    "Backward": "후진",
    "Left": "좌",
    "Right": "우",
    "Jump": "점프",
    "Crouch": "앉기",
    "Sprint": "달리기",
    "Prone": "엎드리기",
    "Inventory": "가방",
    "Cycle_Item_Type": "아이템 종류 바꾸기",
    "Drop_Item": "아이템 버리기",
    "Hide_UI": "UI 숨기기",
    "Screenshot": "스크린샷",
    "Debug_Info": "디버그 정보",
    "Attack_Break": "공격 / 부수기",
    "Pick_Block": "블록 선택",
    "Use_Place": "사용 / 놓기",
    "Open_Chat": "대화 열기",
    "No_Clip": "노 클립",
    "Change_Perspective": "시점 변경",
    "Reload_Shaders": "셰이더 리로드",
    "Fullscreen": "풀스크린",
    "Create_New_World": "새로운 세계 생성",
    "worldNameButton": "월드 이름: ",
    "defaultWorldName": "새로운 세계",
    "worldSeedLabel": "월드 시드: <랜덤>",
    "worldSeedLabel2": "월드 시드: ",
    "worldType": "월드 타입: ",
    "Return_to_Main_Menu": "메인 메뉴로 돌아가기",
    "returnButton": "뒤로",
    "Open_Worlds_Directory": "월드 폴더 열기",
    "YT_Channel": "youtube.com/@finalforeach에서 개발 현황을 확인하세요",
    "Game_version_prealpha": "코스믹 리치 버전 Pre-alpha-",
    "Game_version_alpha": "코스믹 리치 버전 Alpha-",
    "Game_version_beta": "코스믹 리치 버전 Beta-",
    "Game_version_release": "코스믹 리지 버전",
    "MAC_warning": "주의: 지금은 맥OS를 지원하지 않습니다. 게임이 올바르게 작동될 가능성이 낮습니다.",
    "Controller": "컨트롤러",
    "Controllers": "컨트롤러",
    "Controller_info": "감지됨!\n아직 컨트롤러 지원이 부족합니다,\n추후 업데이트를 통해 개선됩니다.",
    "on_state": "켬",
    "off_state": "끔",
    "World_name": "세계-",
    "Screenshot_info": "스크린샷을 저장했습니다",
    "Screenshot_error": "스크린샷 저장중 문제가 발생하였습니다.",
    "Loading": "로딩중",
    "mouseLeftButton": "왼쪽 버튼",
    "mouseMiddleButton": "가운데 버튼",
    "mouseRightButton": "오른쪽 버튼",
    "mouseBackButton": "마우스 버튼 4",
    "mouseForwardButton": "마우스 버튼 5",
    "RuntimeException": "월드를 불러오지 못했습니다: ",
    "creditsGameBy": "게임 제작:",
    "creditsMusic": "음악:",
    "creditsAdditionalProgramming": "프로그래밍 참여:",
    "creditsAdditionalModelling": "모델림 참여:",
    "creditsAdditionalTexturing": "텍스쳐링 참여:",
    "creditsAdditionalMobs": "몹 디자인 참여:",
    "creditsLocalization": "현지화 참여:",
    "multiplayerButton": "멀티 플레이어",
    "multiplayerAddressButton": "주소: ",
    "multiplayerJoinButton": "참가",
    "multiplayerBadDisconnect": "연결 끊김! 사유:",
    "textDisplayInput": "여기에 입력...",
    "skinChangeLabel": "스킨 변경",
    "skinFileDesc": "128x64 픽셀의 PNG 파일",
    "itemCatalogSearch": "검색...",
    "boomboxOctave": "옥타브",
    "boomboxPlaySound": "재생",
    "worldSelectionSearch": "월드 검색...",
    "createWorldGamemode": "게임 모드:",
    "gamemode_survival": "서바이벌",
    "gamemode_creative": "크리에이티브",
    "zone_base:earth": "지구",
    "zone_base:flat": "평지",
    "zone_base:moon": "달",
    "zone_base:void": "공허",
    "mobUnnamed": "언네임드",
    "zone_base:earth_legacy": "지구 (레거시)",
    "comingSoon": "곧 공개...",
    "zone_base:nostalgic_island": "그리운 섬"
}
